#!/usr/bin/env python3

import sys

def sign(n):
    if n > 0:
        return 1
    if n == 0:
        return 0
    return -1

def check(source):
    prev_center = 20
    code_quality = []
    for line_nb, line in enumerate(source.split('\n')):
        quality = 0.
        indent = len(line) - len(line.lstrip(" \t"))
        length = len(line.rstrip())
        if indent % 4:
            quality -= 4
        if length > 79:
            quality -= 4
        new_center = indent + (length - indent) / 2
        d_center = abs(new_center - prev_center)
        if d_center > 16:
            quality -= (d_center - 16) / 14
        code_quality.append(quality)
        prev_center = new_center
    mq = min(code_quality)
    aq = sum(code_quality) / len(code_quality)
    return round(1 + (mq + aq) / 2, 4)
        


for source in sys.argv[1:]:
    print(f"\n------- FILE: {source}")
    with open(source) as source:
        source = source.read()
    quality = check(source)
    lines = len(source.split('\n'))
    print(f"{lines=}")
    print(f"{quality=}")
